#
# Prepare systems for configuration
#
- name: Prepare systems for configuration
  hosts: "tag_Cluster_{{ cluster_prefix }}:&tag_Type_storage"
  become: yes
  vars_files:
    - "vars/{{ varfile }}"
  tasks:

  - name: Remove require tty
    lineinfile: regexp="Defaults\s+requiretty" dest=/etc/sudoers state=absent

  - name: Do not use DNS resolution for SSH
    lineinfile: regexp="Use\s+DNS" dest=/etc/ssh/sshd_config state=absent

  - name: Do not use DNS resolution for SSH
    lineinfile: regexp="^Use\s+DNS" dest=/etc/ssh/sshd_config  line="UseDNS no" state=present

  - name: Restart SSH
    service: name=sshd state=restarted
