#
# Update all Gluster cluster nodes
#
- name: Update all Gluster cluster nodes
  hosts: "tag_Type_storage:tag_Type_storage_client:&tag_Cluster_{{ cluster_prefix }}"
  vars_files:
    - "vars/{{ varfile }}"
  roles:
    - os-update
