#
# Prepare systems for configuration
#
- name: Prepare systems for configuration
  hosts: "tag_Cluster_{{ cluster_prefix }}:&tag_Type_storage"
  become: yes
  vars_files:
    - "vars/{{ varfile }}"
  tasks:

  - name: Remove require tty
    lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent
