#
# Create storage nodes and volumes
#
- name: Create storage nodes and volumes
  any_errors_fatal: true
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "vars/{{ varfile }}"
  vars:
    - ec2_tag_Type: "storage"
    - ec2_instance_type: "{{ ec2_storage_server_instance_type}}"
    - server_count: "{{ storage_servers_count }}"
  roles:
    - python-modules
    - aws-instances
    - aws-disks

#
# Create standalone storage clients
#
- name: Create standalone storage clients
  any_errors_fatal: true
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "vars/{{ varfile }}"
  vars:
    - ec2_tag_Type: "storage-client"
    - ec2_instance_type: "{{ ec2_client_instance_type}}"
    - server_count: "{{ client_servers_count }}"
  roles:
    - aws-instances
