#
# List Gluster cluster nodes information
#
- name: Cluster information
  hosts: "tag_type-storage:tag_type-storage-client:&tag_cluster-{{ cluster_prefix }}"
  tasks:

    - name: Storage node(s)
      debug: msg="{{ name }} - {{ inventory_hostname }}"

    - name: Install brick list file
      become: true
      template: src=files/bricks.txt.ec2.j2 dest=/root/bricks.txt mode=0644
