- hosts: "tag_type-storage:&tag_cluster-{{ cluster_prefix }}"
  become: true
  vars_files:
    - vars/defaults.yml
    - "vars/{{ varfile }}"
  roles:
    - { role: gluster, type: 'storage' }

- hosts: "tag_type-storage-client:&tag_cluster-{{ cluster_prefix }}"
  become: true
  vars_files:
    - vars/defaults.yml
    - "vars/{{ varfile }}"
  roles:
    - { role: gluster, type: 'storage-client' }