#
# List Gluster cluster nodes information
#
- name: Cluster information
  hosts: "tag_type-storage:tag_type-storage-client:&tag_cluster-{{ cluster_prefix }}"
  tasks:

    - name: Storage node(s)
      debug: msg="{{ inventory_hostname }} - {{ hostvars[inventory_hostname].gce_public_ip }}"

    - name: Install brick list file
      become: true
      template: src=files/bricks.txt.j2 dest=/root/bricks.txt mode=0644
