#
# Update all Gluster cluster nodes
#
- name: Update all Gluster cluster nodes
  hosts: "tag_type-storage:tag_type-storage-client:&tag_cluster-{{ cluster_prefix }}"
  vars_files:
    - "vars/{{ varfile }}"
  roles:
    - os-update
