- name: Create storage nodes and volumes
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/defaults.yml
    - "vars/{{ varfile }}"
  roles:
    - python-modules
    - { role: gce-instances, gce_tags: [ "type-storage", "cluster-{{ cluster_prefix }}", "role-{{ role }}" ] }
    - gce-disks