role: storage
gce_tags: [ ]
server_names: |
                {% set comma = joiner(",") %}
                {% for s in range(0, storage_servers_count) -%}
                  {{comma()}}{{ cluster_prefix }}-{{ role }}-{{ s | to_uuid | truncate(6, false, '')}}
                {%- endfor %}