#
# Storage instance default settings
#
# Reference info for settings and pricing
#
# http://docs.ansible.com/ansible/gce_module.html
# https://cloud.google.com/compute/pricing
#

# The number of storage servers in your cluster
storage_servers_count: 2

# The size of each storage server
gce_storage_server_machine_type: n1-standard-2

# If you'd like a dedicated client with tools loaded (for tasks like benchmarking the cluster)
client_servers_count: 0

# The size of each client server
gce_client_server_machine_type: n1-standard-1

# Location and OS image settings for all

# Find available instances with the command: gcloud compute images list
gce_image: centos-7-v20160301
gce_zone: us-central1-b
