- name: Launch instance(s)
  gce:
    instance_names: "{{ server_names.strip().split(',') }}"
    machine_type: "{{ gce_machine_type }}"
    image: "{{ gce_image }}"
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    tags: "{{ gce_tags }}"
    zone: "{{ gce_zone }}"