- name: Launch instance(s)
  gce:
    instance_names: "{{ server_names.strip().split(',') }}"
    machine_type: "{{ gce_machine_type }}"
    image: "{{ gce_image }}"
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    tags: "{{ gce_tags }}"
    zone: "{{ gce_zone }}"
  register: gce

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=300
  with_items: "{{ gce.instance_data }}"