- name: Provision EC2 Instance(s)
  ec2:
    exact_count: "{{ server_count }}"
    count_tag:
      Cluster: "{{ ec2_tag_Cluster }}"
      Type: "{{ ec2_tag_Type }}"
    key_name: "{{ ec2_keypair }}"
    group: "{{ ec2_security_groups }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
    region: "{{ ec2_region }}"
    instance_tags:
      Cluster: "{{ ec2_tag_Cluster }}"
      Type: "{{ ec2_tag_Type }}"
      billing: "{{ ec2_tag_Billing }}"
    assign_public_ip: "{{ assign_public_ip }}"
    wait: true
    volumes:
    - device_name: /dev/sda1
      device_type: "{{ ec2_root_volume_type }}"
      volume_size: "{{ ec2_root_volume_size }}"
      delete_on_termination: true
  register: ec2

- name: Add Name tag to hosts based on ec2_id value
  ec2_tag:
    resource: "{{ item.id }}"
    region: "{{ ec2_region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    tags:
      Name: "{{ ec2_tag_Cluster }}-{{ ec2_tag_Type }}-{{ item.id | hash('sha1') | truncate(6, false, '') }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 10
    timeout: 320
    state: started
  with_items: "{{ ec2.instances}}"