- name: Provision storage disks
  ec2_vol:
    instance: "{{ item.id }}"
    volume_type: "{{ ec2_storage_servers_disk_type }}"
    volume_size: "{{ storage_servers_disk_size_gb }}"
    delete_on_termination: true
  with_items: "{{ ec2.instances }}"
